# Nodemon develop stage
# Build image to run client with nodemon
FROM node:20-alpine AS nodemon-dev

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

CMD ["npm", "run", "dev"]

### Develop production multistage

# Develop build stage
# Build image to build client's .next/
FROM node:20 AS builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ENV NEXT_PUBLIC_API_URL=http://localhost:4000/api

RUN npm run build

# Develop production stage
# Build image to run builder with only production dependencies
FROM node:20-alpine AS prod

WORKDIR /usr/src/app

COPY --chown=node:node --from=builder /usr/src/app/.next ./.next
COPY --chown=node:node --from=builder /usr/src/app/public ./public
COPY --chown=node:node --from=builder /usr/src/app/package.json ./package.json
COPY --chown=node:node --from=builder /usr/src/app/package-lock.json ./package-lock.json

RUN npm ci --only=production

USER node

EXPOSE 3000

CMD ["npm", "start"]