# In-docker build stage
# Build image to build client in the docker network
FROM node:20 AS builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ENV NEXT_PUBLIC_API_URL=http://server:4000/api

RUN npm run build

# In-docker production stage
# Build image to run client in the docker network
FROM node:20-alpine AS prod

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/.next ./.next
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/package.json ./package.json
COPY --from=builder /usr/src/app/package-lock.json ./package-lock.json

RUN npm ci --only=production

USER node

EXPOSE 3000

CMD ["npm", "start"]
