services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - POSTGRES_URL=postgresql://postgres:example@postgres:5432
    command: ['npm', 'start']
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=example
