services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - POSTGRES_URL=postgresql://postgres:example@postgres:5432
      - MONGO_URL=mongodb://root:example@mongo:27017
      - JWT_SECRET=secret1211
    command: ['npm', 'start']
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
