# Nodemon develop stage
FROM node:20-slim AS dev

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

CMD ["npm", "run", "dev"]

# Local migration stage
FROM node:20-slim AS migration

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ARG POSTGRES_URL
ARG MONGO_URL
ENV POSTGRES_URL=${POSTGRES_URL}
ENV MONGO_URL=${MONGO_URL}

CMD ["sh", "-c", "npm run migrate:up && npm run seed"]
